<?php
/*
 * ****************************************************************************
 *  * Module generated by TDMCreate from TDM "http://www.tdmxoops.net"
 * ****************************************************************************
 * xsitemap - MODULE FOR XOOPS CMS
 * Copyright (c) Urbanspaceman (http://www.takeaweb.it)
 *
 * You may not change or alter any portion of this comment or credits
 * of supporting developers from this source code or any supporting source code
 * which is considered copyrighted (c) material of the original comment or credit authors.
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * ****************************************************************************
 */
/**
 * Module: xsitemap
 *
 * @package    module\xsitemap\admin
 * @author     XOOPS Module Development Team
 * @author     http://www.takeaweb.it  Urbanspaceman
 * @copyright  http://www.takeaweb.it Urbanspaceman
 * @copyright  http://xoops.org 2001-2017 XOOPS Project
 * @license    http://www.fsf.org/copyleft/gpl.html GNU public license
 * @link       http://xoops.org XOOPS
 * @since      1.00
 *
 * @uses Xmf\Module\Admin
 */

require_once __DIR__ . '/admin_header.php';

$moduleAdmin = \Xmf\Module\Admin::getInstance();

xoops_cp_header();

// Get online plugin info
//$countPlugins       = $pluginHandler->getCount();
$criteria           = new Criteria('plugin_online', 1);
$onlinePluginObjs   = $pluginHandler->getAll($criteria);
$countPluginsOnline = (!empty($onlinePluginObjs)) ? count($onlinePluginObjs) : 0;
$onlinePluginArray  = array();
foreach($onlinePluginObjs as $onlineObj) {
    $onlinePluginArray[] = $onlineObj->getVar('plugin_name');
}
natsort($onlinePluginArray);
$onlinePluginNames = implode(', ', $onlinePluginArray);

// get offline plugin info
$criteria            = new Criteria('plugin_online', 0);
$offlinePluginObjs   = $pluginHandler->getAll($criteria);
$countPluginsOffline = (!empty($offlinePluginObjs)) ? count($offlinePluginObjs) : 0;
$offlinePluginArray  = array();
foreach($offlinePluginObjs as $offlineObj) {
    $offlinePluginArray[] = $offlineObj->getVar('plugin_name');
}
natsort($offlinePluginArray);
$offlinePluginNames = implode(', ', $offlinePluginArray);

$moduleAdmin->addInfoBox(_AM_XSITEMAP_MANAGER_INDEX);
// display number of plugins online
$moduleAdmin->addInfoBoxLine(sprintf(_AM_XSITEMAP_THEREARE_PLUGIN_ONLINE, $countPluginsOnline), '', 'green');
// display number of plugins offline
$moduleAdmin->addInfoBoxLine(sprintf(_AM_XSITEMAP_THEREARE_PLUGIN_OFFLINE, $countPluginsOffline), '',  'green');
// display total number of plugins
$moduleAdmin->addInfoBoxLine(sprintf(_AM_XSITEMAP_THEREARE_PLUGIN, $countPluginsOnline + $countPluginsOffline), '',  'green');

$moduleAdmin->addConfigBoxLine(sprintf(_AM_XSITEMAP_PLUGIN_ONLINE_NAMES, $onlinePluginNames), 'information');
$moduleAdmin->addConfigBoxLine(sprintf(_AM_XSITEMAP_PLUGIN_OFFLINE_NAMES, $offlinePluginNames), 'information');

$moduleAdmin->displayNavigation(basename(__FILE__));
$moduleAdmin->displayIndex();

include __DIR__ . '/admin_footer.php';
