<?php namespace XoopsModules\Xsitemap;

/*
 * ****************************************************************************
 * Module generated by TDMCreate from TDM "http://www.tdmxoops.net"
 * ****************************************************************************
 * xsitemap - MODULE FOR XOOPS CMS
 * Copyright (c) Urbanspaceman (http://www.takeaweb.it)
 *
 * You may not change or alter any portion of this comment or credits
 * of supporting developers from this source code or any supporting source code
 * which is considered copyrighted (c) material of the original comment or credit authors.
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 */

/**
 * Module: xsitemap
 *
 * @package    module\Xsitemap\class
 * @author     Urbanspaceman (http://www.takeaweb.it)
 * @copyright  Urbanspaceman (http://www.takeaweb.it)
 * @license    http://www.fsf.org/copyleft/gpl.html GNU public license
 * @since      1.00
 */
class DummyObject extends \XoopsObject
{
    /**
     * constructor
     * @param        $row
     * @param string $id_name
     * @param string $pid_name
     * @param string $title_name
     */
    public function __construct(&$row, $id_name = 'cid', $pid_name = 'pid', $title_name = 'title')
    {
        parent::__construct();
        $this->initVar($id_name, XOBJ_DTYPE_INT, $row[$id_name]);
        $this->initVar($pid_name, XOBJ_DTYPE_INT, $row[$pid_name]);
        $this->initVar($title_name, XOBJ_DTYPE_TXTBOX, $row[$title_name]);
    }
}
